/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DatePickerCarrouselComponent: typeof import('./src/components/DatePickerCarrouselComponent.vue')['default']
    ProfesionalCardComponent: typeof import('./src/components/ProfesionalCardComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceAppointmentCardComponent: typeof import('./src/components/ServiceAppointmentCardComponent.vue')['default']
    ServiceCardComponent: typeof import('./src/components/ServiceCardComponent.vue')['default']
    WhatsappButtonComponent: typeof import('./src/components/WhatsappButtonComponent.vue')['default']
  }
}
